### PR TITLE
Split SAE training eval code into training and post-training

### PR DESCRIPTION
**Pull request by Stevinson**
This is still WIP but thought it best to get some eyes on it in case it wasn't what was wanted. The PR includes the following:

* I have moved the evaluation code into an `Evaluator` class. The idea here was that this would be easier to extend and also that there are two different evaluation contexts, `TrainingEval` and `PostTrainingEval`. This was done so that a cheaper form of evaluation can be done during training, such that one can get an idea of training but one would want to perform a full evaluation on a model that is already trained.
  * I've split `evals.py` into `evaluator.py` and `eval_utils.py`. I haven't changed the evaluation code itself.
  * I've also left the existing evaluation code as is.
  * Specific evaluations can be ran by adding them to the `EvalConfig`
* I had a crack at starting some documentation for the validation and evaluation experiment tracking. This can be found in `experiment_tracking.md`. Given that I was both reading the codebase and learning about training SAEs for the first time, I thought it a good time to note down what gets tracked and why.
* Adding functionality to load a `HookedViT` from file in the SAE training flow. This is done by just adding an optional `vit_model_cfg` to the `VisionModelSAERunnerConfig` and extending the current functionality (i.e. checking if `local` is in the model name and adding an `is_local` variable to the existing `is_clip` and `is_timm` variables).
* I refactored a few bits of code as there seemed to be places where things were replicated:
  * `load_dataset` was duplicated so I refactored this into a shared function.
  * A small bug fix where the final checkpoint was causing an indexing error.

### CODE REVIEW

**Comment by soniajoseph** [comment]
Thank you! Looks good, could you fix the merge conflicts?

**Comment by soniajoseph** [comment]
The documentation is also a nice touch

**Comment by ekg15** [comment]
Going to take a look at this later today or tomorrow - I also have some validation code written, unfortunately. We seem to have gone about it in different ways, so there is the possibility of some benefits to both that can be merged.

**Comment by ekg15** [comment]
In general it looks good - does it work? I like the refactoring of the load_dataset - I will say, it's more typical for validation to be a training loop in ML repos. I'll probably create a PR with my changes (far more lightweight and temporary in nature) and I think we should layer your changes in with mine

**Comment by PraneetNeuro** [comment]
@Stevinson we've moved your sae validation code to a new branch [edward-post-training-sae-validation](https://github.com/soniajoseph/ViT-Prisma/tree/edward-post-training-sae-validation). Feel free to update your work over there.

**Pull request closed without merging**
